spring.application.name=aria-backend

# MongoDB Atlas
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://aria_admin:SENHA_PLACEHOLDER@cluster0.td51izl.mongodb.net/ariadb?appName=Cluster0}

server.port=8080

# Logs úteis durante o desenvolvimento
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# JWT
jwt.secret=${JWT_SECRET:chave-temporaria-de-desenvolvimento-troque-em-producao-min-32-chars}
jwt.expiration-ms=86400000


# DEBUG
#logging.level.org.springframework.security=DEBUG